name: CI

on:
  pull_request:
    branches:
      - main
      - feature/ci-pipeline
  workflow_dispatch:

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    env:
      API_URL: ${{ secrets.API_URL }}

    steps:
      - name: Checkout do código
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Instalar dependências
        run: npm ci

      - name: Generate environment.ts
        run: |
          mkdir -p src/environments
          cat > src/environments/environment.ts <<EOF
          export const environment = {
            production: true,
            apiUrl: '${API_URL}'
          };
          EOF

      - name: Executar lint
        run: npm run lint

      - name: Executar build
        run: npm run build -- --configuration production
